name: CI

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]
      - name: run RStudio Connect
        run: |
          make dev
        RSC_LICENSE: ${{ secrets.RSC_LICENSE }}

      - name: Run tests
        shell: bash
        run: |
          pytest airflow_connect
